traj_follower_cpp:
  ros__parameters:
    wheelbase: 1.20
    lookahead_gain: 1.30
    lookahead_min_distance: 3.0
    use_preview: true
    preview_time: 0.8
    l0: 1.3
    tau: 0.45
    steering_tire_angle_gain: 1.65
    use_external_target_vel: false

